### ISSUE TITLE
SimplePermissions unable to update.

### ISSUE THREAD

**Issue by raxixor** [Joe4evr/Discord.Addons#7]
Trying to update SimplePermissions from v0.7.15-a to v0.8.19-rc

Error message:
![image](https://cloud.githubusercontent.com/assets/1861988/23157448/f7da380a-f823-11e6-8107-183cae6b7add.png)

**Comment by Joe4evr** [comment]
This is because the Net Standard dependency went up from 1.3 to 1.6 (which apparently doesn't have a full framework equivalent if 4.6.2 doesn't fit) because there's no way to get the loaded assembly names for the new debug command on lower versions (so bad).

If you port your code to a .NET Core project and target `NETCoreApp1.0` it will work.

**Comment by raxixor** [comment]
Got it to work, thanks.
